server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g115-sprint-task6-1-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true